#!/usr/bin/env perl

# This script is based off of Perl101's crank script.
# See http://github.com/petdance/perl101
# http://www.perl101.org

use strict;
use warnings;

use Getopt::Long;
use Template ();

my $buildpath = 'build';

GetOptions(
    'buildpath:s' => \$buildpath,
) or exit;

if ( ! -d $buildpath || ! -w $buildpath ) {
    die "Buildpath ($buildpath) doesn't exist or is not writable";
}

my %defaults = (
    INCLUDE_PATH => [ qw( template ) ],
    OUTPUT_PATH  => $buildpath,
    PRE_CHOMP    => 1,
    POST_CHOMP   => 0,
);

my $tt = Template->new( \%defaults );
my $vars = {};

$vars->{IMAGE_DIR} = 'img';

chomp ($vars->{meta_description} = <<'EOT');
A networking and social group for discussion on Perl, located in
Thousand Oaks, California
EOT
$vars->{meta_author} = 'Tommy Stanton';
chomp ($vars->{header} = <<'EOT');
ThousandOaks.pm:
Thousand Oaks Perl Mongers
EOT
$vars->{title} = $vars->{header};
$vars->{title} =~ s/\n/ /g;

$vars->{description} = $vars->{meta_description};

$vars->{next_meeting} = {
    details => undef,
    mailing_list_entry => undef,
    date    => {
        day  => q{Wednesday, August 10, 2011},
        time => q{7:00 PM},
    },
    location => {
        name    => q{ValueClick Media},
        address => undef,
    },
    parking => undef,
    map_link => undef,
};
chomp ($vars->{next_meeting}->{details} = <<'EOT');
We meet on the 2nd Wednesday of every month.  Here are the details for
the next confirmed meeting.
EOT
chomp ($vars->{next_meeting}->{location}->{address} = <<'EOT');
30699 Russel Ranch Rd
Westlake Village, CA 91362
EOT
chomp ($vars->{next_meeting}->{parking}->[0]->{note} = <<'EOT');
There is a giant parking lot right in front of the building with plenty
of free parking. :)
EOT

$vars->{next_meeting}->{map_link} =
    q|http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=30699+Russel+Ranch+Rd.+Westlake+Village,+CA&aq=&sll=37.0625,-95.677068&sspn=44.793449,79.013672&ie=UTF8&hq=&hnear=30699+Russell+Ranch+Rd,+Westlake+Village,+Los+Angeles,+California+91362&ll=34.152248,-118.797859&spn=0.005744,0.009645&t=h&z=17|;

$vars->{presentations} = [
    {   presenter   => undef,
        title       => undef,
        description => undef,
    },
    {   presenter   => undef,
        title       => undef,
        description => undef,
    },
];
chomp ($vars->{presentations}->[0]->{description} = <<'EOT');
EOT
chomp ($vars->{presentations}->[1]->{description} = <<'EOT');
EOT

$vars->{mailing_list} = {
    post_email => q{thousand-oaks-pm@pm.org},
    subscribe_email => q{thousand-oaks-pm-request@pm.org},
    subscribe_url => q{http://mail.pm.org/mailman/listinfo/thousand-oaks-pm},
    archives_url => q{http://mail.pm.org/pipermail/thousand-oaks-pm/},
};


chomp ($vars->{content} = <<'EOT');
Directions to get to ValueClick:<br /><br />Take the 101 Freeway to the
Lindero Canyon Road exit and head north.  Pass the Memorial Park on your
right and turn right at the 2nd light for Russell Ranch Road (you will
see a Chiptole at that corner).  Pass the Costco to your right, and then
take the first right into the parking lot (there is a little yellow
parcel box that you can use in spotting the driveway that you need to
turn into).  Turn left toward the glass doors in the far corner.
Someone will be waiting to let you in downstairs, at the glass doors.
EOT

$tt->process( 'page.tt', $vars, 'index.html' ) || die $tt->error;
